# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
# ***********************************************************************
# DO NOT REMOVE OR COMMENT OUT ANY LINES IN THIS FILE.
# SIMPLY APPEND THE REQUIRED VALUES AGAINST THE PARAMETER OF YOUR CHOICE.
# ***********************************************************************

# ***********************************************************************
# BuildStreaM (BSM)) Configuration for configuring CI/CD pipeline to automate image building and deploy
# ***********************************************************************

# Mandatory: Enable or disable build stream pipeline
# Accepted values: boolean values - (true or false) or(yes or no)
# Default: false
enable_build_stream: false

# Optional: Build Stream API server host IP
# Accepted values: public IP address of OIM or admin IP of OIM
# Default is admin IP of OIM
build_stream_host_ip:

# Mandatory: Build Stream API server port
# Accepted values: valid port number (1-65535) which is free
# Default: 8010
build_stream_port: 8010

# Conditional Mandatory: AArch64 inventory host IP for aarch64 builds
# Accepted values: admin IP of aarch64 host where OS is installed
# Default none - by deafult aarch64 builds will not be generated
aarch64_inventory_host_ip:

# PostgreSQL configuration for build stream
postgres_db_name: "build_stream_db"