# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: "Encrypt credentials file - {{ credential_type }}"
  block:
    - name: "Check if credentials file is encrypted - {{ credential_type }}"
      ansible.builtin.shell: >-
        set -o pipefail && head -n1 {{ credential_file_path }} | grep -q '\$ANSIBLE_VAULT;'
      register: file_encrypted
      changed_when: false
      failed_when: false

    - name: "Check if vault password file exists - {{ credential_type }}"
      ansible.builtin.stat:
        path: "{{ vault_password_file }}"
      register: vault_key_status

    - name: "Ensure credentials are encrypted - {{ credential_type }}"
      ansible.builtin.command: >-
        ansible-vault encrypt {{ credential_file_path }}
        --vault-password-file {{ vault_password_file }}
      when:
        - credential_file_path is file
        - file_encrypted.rc != 0
        - vault_key_status.stat.exists
      changed_when: false
