# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: "Encrypt {{ credential_type }} credentials file"
  block:
    - name: "Check if vault key exists for {{ credential_type }}"
      ansible.builtin.stat:
        path: "{{ vault_password_file }}"
      register: vault_key_status

    - name: "Create and save vault key for {{ credential_type }} if not exists"
      ansible.builtin.lineinfile:
        path: "{{ vault_password_file }}"
        line: "{{ lookup('password', '/dev/null chars=ascii_letters') }}"
        mode: "0600"
        owner: root
        create: true
      when: not vault_key_status.stat.exists

    - name: "Encrypt {{ credential_type }} credentials"
      ansible.builtin.command: >-
        ansible-vault encrypt {{ credential_file_path }}
        --vault-password-file {{ vault_password_file }}
      changed_when: false
