# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set common library path
  ansible.builtin.set_fact:
    module_utils_path: "{{ role_path }}/../../../../common/library/module_utils/"

- name: Fetch credentials
  ansible.builtin.include_tasks: fetch_credentials.yml
  loop: "{{ omnia_credentials | dict2items }}"
  loop_control:
    loop_var: service

- name: Include updated credentials
  block:
    - name: Set variables for common task
      ansible.builtin.set_fact:
        cred_file_path: "{{ omnia_credential_file }}"
        cred_vault_path: "{{ omnia_credential_vault_path }}"
    
    - name: Include omnia credentials using common task
      ansible.builtin.include_tasks: "{{ role_path }}/../../../../common/tasks/common/decrypt_include_encrypt.yml"
      vars:
        credential_file_path: "{{ cred_file_path }}"
        vault_password_file: "{{ cred_vault_path }}"

- name: Include updated build stream credentials
  block:
    - name: Set variables for common task
      ansible.builtin.set_fact:
        cred_file_path: "{{ bs_credential_file }}"
        cred_vault_path: "{{ bs_credential_vault_path }}"
    
    - name: Include build stream credentials using common task
      ansible.builtin.include_tasks: "{{ role_path }}/../../../../common/tasks/common/decrypt_include_encrypt.yml"
      vars:
        credential_file_path: "{{ cred_file_path }}"
        vault_password_file: "{{ cred_vault_path }}"
  when: 
    - enable_build_stream | default(false) | bool
    - bs_cred_file_status | default(false)

- name: Update build_stream_oauth_credentials.yml with hashed password
  ansible.builtin.include_tasks: update_bs_credential_file.yml
  when: 
    - enable_build_stream | default(false) | bool
    - build_stream_username is defined
    - build_stream_password is defined

- name: Encrypt omnia credentials config
  ansible.builtin.include_tasks: encrypt_credentials_file.yml
  vars:
    credential_type: "Omnia"
    credential_file_path: "{{ omnia_credential_file }}"
    vault_password_file: "{{ omnia_credential_vault_path }}"
