# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set common library path
  ansible.builtin.set_fact:
    module_utils_path: "{{ role_path }}/../../../../common/library/module_utils/"

- name: Pre-load build stream credentials if they exist
  when:
    - enable_build_stream | default(false) | bool
    - credential_files[1].file_path is file
  block:
    - name: Set variables for common task
      ansible.builtin.set_fact:
        cred_file_path: "{{ credential_files[1].file_path }}"
        cred_vault_path: "{{ credential_files[1].vault_path }}"

    - name: Include build stream credentials using common task
      ansible.builtin.include_tasks: "{{ role_path }}/../../../../common/tasks/common/decrypt_include_encrypt.yml"
      vars:
        credential_file_path: "{{ cred_file_path }}"
        vault_password_file: "{{ cred_vault_path }}"

    - name: Set build_stream variables from auth_registration
      ansible.builtin.set_fact:
        build_stream_auth_username: "{{ auth_registration.username | default('') }}"
        build_stream_auth_password_hash: "{{ auth_registration.password_hash | default('') }}"
      no_log: true

- name: Fetch credentials
  ansible.builtin.include_tasks: fetch_credentials.yml
  loop: "{{ omnia_credentials | dict2items }}"
  loop_control:
    loop_var: service

- name: Include updated credentials
  ansible.builtin.include_tasks: "{{ role_path }}/../../../../common/tasks/common/decrypt_include_encrypt.yml"
  loop: "{{ credential_files }}"
  loop_control:
    loop_var: cred_config
  when: 
    - cred_config.condition | default(true) | bool
    - cred_config.file_path is file
  vars:
    credential_file_path: "{{ cred_config.file_path }}"
    vault_password_file: "{{ cred_config.vault_path }}"
