- name: Set build_stream_job_id from environment
  ansible.builtin.set_fact:
    build_stream_job_id: "{{ job_id | default(lookup('env', 'job_id') | default('')) }}"

- name: Set image_key from environment
  ansible.builtin.set_fact:
    image_key: "{{ image_key | default(lookup('env', 'image_key') | default('')) }}"

- name: Validate build stream inputs
  ansible.builtin.fail:
    msg: "{{ build_stream_job_id_absent }}"
  when:
    - enable_build_stream | default(false) | bool
    - ((build_stream_job_id | default('') | length) == 0) and ((image_key | default('') | length) == 0)

- name: set compute_image_suffix
  ansible.builtin.set_fact:
    compute_image_suffix: "{{ (build_stream_job_id ~ '-' ~ (image_key | default(''))) | regex_replace('^-+', '') }}"

- name: debug
  ansible.builtin.debug:
    var: compute_image_suffix
