# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set the functional_group_name
  ansible.builtin.set_fact:
    functional_group_name: "{{ item }}"

- name: debug job-id
  ansible.builtin.debug:
    var: build_stream_job_id

- name: debug compute image suffix
  ansible.builtin.debug:
    var: compute_image_suffix

- name: debug image key
  ansible.builtin.debug:
    var: image_key

- name: Verify image, kernel and initramfs in S3 (build stream and image-key)
  ansible.builtin.shell: |
    set -o pipefail && \
    s3cmd ls -Hr s3://boot-images | \
    grep {{ functional_group_name }} | \
    grep {{ compute_image_suffix }} | \
    grep {{ hostvars['localhost']['cluster_os_version'] }} | awk '{print $4}' | sed 's|s3://||'
  changed_when: false
  failed_when: false
  register: verify_s3_image_build_stream
  when:
    - enable_build_stream | default(false)
    - (compute_image_suffix | default('')) != ''

- name: Verify image, kernel and initramfs in S3 (default)
  ansible.builtin.shell: |
    set -o pipefail && \
    s3cmd ls -Hr s3://boot-images | \
    grep {{ functional_group_name }} | \
    grep {{ hostvars['localhost']['cluster_os_version'] }} | awk '{print $4}' | sed 's|s3://||'
  changed_when: false
  failed_when: false
  register: verify_s3_image
  when:
    - not enable_build_stream

- name: Set kernel and initrd variables (build stream)
  ansible.builtin.set_fact:
    kernel: "{{ verify_s3_image_build_stream.stdout_lines | select('search', 'vmlinuz') | list | first }}"
    initrd: "{{ verify_s3_image_build_stream.stdout_lines | select('search', 'initramfs') | list | first }}"
  when:
    - enable_build_stream
    - (compute_image_suffix | default('')) != ''

- name: Set kernel and initrd variables (default)
  ansible.builtin.set_fact:
    kernel: "{{ verify_s3_image.stdout_lines | select('search', 'vmlinuz') | list | first }}"
    initrd: "{{ verify_s3_image.stdout_lines | select('search', 'initramfs') | list | first }}"
  when:
    - not enable_build_stream

- name: Load bss template - {{ functional_group_name }}
  ansible.builtin.template:
    src: "{{ bss_template }}"
    dest: "{{ bss_dir }}/bss-{{ functional_group_name }}.yaml"
    mode: "{{ hostvars['localhost']['file_permissions_644'] }}"

- name: Delete boot configuration - {{ functional_group_name }}
  ansible.builtin.command: /usr/bin/ochami bss boot params delete --no-confirm -f yaml -d @{{ openchami_work_dir }}/boot/bss-{{ functional_group_name }}.yaml
  changed_when: true
  failed_when: false

- name: Set boot configuration - {{ functional_group_name }}
  ansible.builtin.command: /usr/bin/ochami bss boot params set -f yaml -d @{{ openchami_work_dir }}/boot/bss-{{ functional_group_name }}.yaml
  changed_when: true
