# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Delete ci group configuration - common
  ansible.builtin.command: /usr/bin/ochami cloud-init group delete --no-confirm -f yaml -d @{{ ci_group_common_dest }}
  changed_when: true
  failed_when: false

- name: Include software configuration for RACADM cloud-init
  ansible.builtin.include_vars:
    file: "{{ software_config_file_path }}"
    name: software_config

- name: Determine if RACADM installation should be enabled
  block:
    - name: Set admin_debug_packages_enabled fact
      ansible.builtin.set_fact:
        admin_debug_packages_enabled: "{{ software_config.softwares | selectattr('name', 'equalto', 'admin_debug_packages') | list | length > 0 }}"  # noqa: yaml[line-length]

    - name: Load admin_debug_packages.json
      ansible.builtin.include_vars:
        file: "{{ input_project_dir }}/config/x86_64/{{ software_config.cluster_os_type }}/{{ software_config.cluster_os_version }}/admin_debug_packages.json"  # noqa: yaml[line-length]
        name: admin_debug_packages_data
      when: admin_debug_packages_enabled

    - name: Check if racadm tarball exists in admin_debug_packages
      ansible.builtin.set_fact:
        racadm_tarball_list: "{{ admin_debug_packages_data.admin_debug_packages.cluster | selectattr('package', 'search', 'racadm') | selectattr('type', 'equalto', 'tarball') | list }}"  # noqa: yaml[line-length]
      when: admin_debug_packages_enabled

    - name: Extract racadm tarball name
      ansible.builtin.set_fact:
        racadm_tarball_name: "{{ racadm_tarball_list[0].package | default('') }}"
        racadm_tarball_found: true
      when: admin_debug_packages_enabled and racadm_tarball_list | length > 0

    - name: Set enable_racadm_install fact
      ansible.builtin.set_fact:
        enable_racadm_install: "{{ admin_debug_packages_enabled and racadm_tarball_found | default(false) }}"

- name: Run pulp status command to get pulp configuration for cloud-init
  ansible.builtin.command: /usr/local/bin/pulp status
  changed_when: false
  register: cloud_init_pulp_status_output
  delegate_to: localhost
  connection: local

- name: Set pulp connection variables
  ansible.builtin.set_fact:
    pulp_content_origin: "{{ (cloud_init_pulp_status_output.stdout | from_json).content_settings.content_origin }}"

- name: Set fact for pulp protocol, ip and port
  ansible.builtin.set_fact:
    pulp_protocol: "{{ pulp_content_origin | urlsplit('scheme') | lower }}"
    pulp_server_ip: "{{ pulp_content_origin | urlsplit('hostname') }}"
    pulp_server_port: "{{ pulp_content_origin | urlsplit('port') }}"

- name: Render ci group common template
  ansible.builtin.template:
    src: "{{ ci_group_common_template }}"
    dest: "{{ ci_group_common_dest }}"
    mode: "{{ hostvars['localhost']['file_permissions_644'] }}"

- name: Set ci group configuration - common
  ansible.builtin.command: /usr/bin/ochami cloud-init group set -f yaml -d @{{ ci_group_common_dest }}
  changed_when: true
