# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Initialize list of tags
  ansible.builtin.set_fact:
    omnia_run_tags: "{{ ansible_run_tags | default([]) }}"
  when: omnia_run_tags is not defined

- name: Validate and include Omnia credential file if it exists
  ansible.builtin.include_tasks: validate_and_include_cred_file.yml
  vars:
    credential_type: "Omnia"
    credential_file_path: "{{ omnia_credential_file }}"
    status_var_name: "omnia_cred_file_status"
    vault_password_file: "{{ omnia_credential_vault_path }}"

- name: Load build_stream_config.yml to check if enabled
  block:
    - name: Include build_stream_config.yml
      ansible.builtin.include_vars:
        file: "{{ input_project_dir }}/build_stream_config.yml"
      register: include_build_stream_config
  rescue:
    - name: Set enable_build_stream to false if config not found
      ansible.builtin.set_fact:
        enable_build_stream: false

- name: Validate and include Build Stream credential file if it exists
  ansible.builtin.include_tasks: validate_and_include_cred_file.yml
  when: enable_build_stream
  vars:
    credential_type: "Build Stream"
    credential_file_path: "{{ bs_credential_file }}"
    status_var_name: "bs_cred_file_status"
    vault_password_file: "{{ bs_credential_vault_path }}"

- name: Include pre_requisite.yml
  ansible.builtin.include_tasks: pre_requisite.yml
