# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Select only the omnia_build_stream service name
  ansible.builtin.set_fact:
    build_stream_services: "{{ ansible_facts['services'].keys() | select('match', '^omnia_build_stream') | list }}"

- name: Stop all matching omnia_build_stream services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ build_stream_services }}"
  when:
    - item in ansible_facts.services
    - ansible_facts.services[item].state == 'running'

- name: Get omnia_build_stream container files
  ansible.builtin.find:
    paths: "{{ quadlet_dir }}"
    patterns: 'omnia_build_stream*'
    file_type: file
  register: found_files

- name: Get the list of omnia build_stream paths
  ansible.builtin.set_fact:
    build_stream_quad_path_list: "{{ found_files.files | map(attribute='path') | list }}"

- name: Remove omnia_build_stream systemd unit files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ build_stream_quad_path_list }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Get info about omnia_build_stream container
  containers.podman.podman_container_info:
    name: "{{ build_stream_container_name }}"
  register: podinfo
  failed_when: false

- name: Stop build_stream container only if it exists
  containers.podman.podman_container:
    name: "{{ build_stream_container_name }}"
    state: stopped
  when: podinfo.containers | length > 0

- name: Remove omnia_build_stream containers
  containers.podman.podman_container:
    name: "{{ build_stream_container_name }}"
    state: absent
    force_delete: true
  when: podinfo.containers | length > 0

- name: Remove build_stream cleanup directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    force: true
  register: directory_deletion
  until: directory_deletion is not failed
  retries: "{{ max_retries }}"
  loop: "{{ build_stream_cleanup_directory }}"

- name: Check if target file exists
  ansible.builtin.stat:
    path: "{{ omnia_target }}"
  register: p

- name: Remove all omnia_build_stream services from omnia.target
  ansible.builtin.replace:
    path: "{{ omnia_target }}"
    regexp: "{{ build_stream_container_name }}.service"
    replace: ''
  when: p.stat.exists
