# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Load build stream configuration from input directory
  ansible.builtin.include_vars:
    file: "{{ hostvars['localhost']['input_project_dir'] }}/build_stream_config.yml"
  delegate_to: localhost

- name: Read BSM API certificate from localhost
  ansible.builtin.slurp:
    src: "{{ gitlab_bs_cert_path }}"
  delegate_to: localhost
  register: _bs_cert_read

- name: Set pipeline variable facts
  ansible.builtin.set_fact:
    _gitlab_bsm_api_url: "https://{{ build_stream_host_ip }}:{{ build_stream_port | default('8010') }}"
    _gitlab_bs_auth_username: "{{ hostvars['localhost']['build_stream_auth_username'] | default('') }}"
    _gitlab_bs_auth_password: "{{ hostvars['localhost']['build_stream_auth_password'] | default('') }}"
    _gitlab_bs_api_cert: "{{ _bs_cert_read.content | b64decode }}"
  no_log: true

- name: Set GitLab pipeline variables for build stream auth
  ansible.builtin.uri:
    url: >-
      {{ gitlab_external_url_computed }}/api/v4/projects/{{ gitlab_project_id
      }}/variables/{{ item.key }}
    method: GET
    headers:
      PRIVATE-TOKEN: "{{ gitlab_root_token }}"
    validate_certs: false
    status_code: "{{ gitlab_pipeline_var_check_status_codes }}"
  register: _pipeline_var_check
  loop: "{{ gitlab_pipeline_bs_variables }}"
  loop_control:
    label: "{{ item.key }}"
  no_log: true

- name: Create GitLab pipeline variable when it does not exist
  ansible.builtin.uri:
    url: "{{ gitlab_external_url_computed }}/api/v4/projects/{{ gitlab_project_id }}/variables"
    method: POST
    headers:
      PRIVATE-TOKEN: "{{ gitlab_root_token }}"
    body_format: json
    body:
      key: "{{ item.item.key }}"
      value: "{{ item.item.value }}"
      variable_type: "{{ item.item.variable_type }}"
      masked: "{{ item.item.masked }}"
      protected: false
    validate_certs: false
    status_code: "{{ gitlab_pipeline_var_create_status_codes }}"
  when: item.status == 404
  loop: "{{ _pipeline_var_check.results }}"
  loop_control:
    label: "{{ item.item.key }}"
  no_log: true

- name: Update GitLab pipeline variable when it already exists
  ansible.builtin.uri:
    url: "{{ gitlab_external_url_computed }}/api/v4/projects/{{ gitlab_project_id }}/variables/{{ item.item.key }}"
    method: PUT
    headers:
      PRIVATE-TOKEN: "{{ gitlab_root_token }}"
    body_format: json
    body:
      value: "{{ item.item.value }}"
      variable_type: "{{ item.item.variable_type }}"
      masked: "{{ item.item.masked }}"
      protected: false
    validate_certs: false
    status_code: "{{ gitlab_pipeline_var_update_status_codes }}"
  when: item.status == 200
  loop: "{{ _pipeline_var_check.results }}"
  loop_control:
    label: "{{ item.item.key }}"
  no_log: true
